SystemOrganization addCategory: #'Pillar-BookTester'!
SystemOrganization addCategory: #'Pillar-BookTester-Annotations'!
SystemOrganization addCategory: #'Pillar-BookTester-Annotations-Tests'!
SystemOrganization addCategory: #'Pillar-BookTester-CommandLine'!
SystemOrganization addCategory: #'Pillar-BookTester-Visitor'!
SystemOrganization addCategory: #'Pillar-BookTester-Visitor-Tests'!
ganization addCategory: #'Pillar-BookTester-Visitor-Tests'!
