Class {
	#name : #PRLevelNumberPrinterTest,
	#superclass : #PRTitlePrinterTest,
	#category : 'Pillar-Tests-ExporterCore-LevelPrinter'
}

{ #category : #requirement }
PRLevelNumberPrinterTest >> actualClass [
	^ PRLevelNumberPrinter
]

{ #category : #requirement }
PRLevelNumberPrinterTest >> representationOf26 [
	^ '26'
]

{ #category : #requirement }
PRLevelNumberPrinterTest >> representationOf27 [
	^ '27'
]

{ #category : #requirement }
PRLevelNumberPrinterTest >> representationOfOne [
	^ '1'
]
