SystemOrganization addCategory: #'Pillar-Model'!
SystemOrganization addCategory: 'Pillar-Model-BasicRoots'!
SystemOrganization addCategory: 'Pillar-Model-Document'!
SystemOrganization addCategory: 'Pillar-Model-Document-List'!
SystemOrganization addCategory: 'Pillar-Model-Exceptions'!
SystemOrganization addCategory: 'Pillar-Model-Feature - structures'!
SystemOrganization addCategory: 'Pillar-Model-Numbering'!
SystemOrganization addCategory: 'Pillar-Model-ScriptLanguage'!
SystemOrganization addCategory: 'Pillar-Model-Toc'!
SystemOrganization addCategory: 'Pillar-Model-Visitor'!
SystemOrganization addCategory: 'Pillar-Model-Visitor - Non Core'!
