#!/bin/bash
set -euo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'
# preamble from https://disconnected.systems/blog/another-bash-strict-mode/

# ensure meaningful default values for required environment variables
: "${TEXLIVE_RELEASE:=2021}"
: "${TEXLIVE_MIRROR:="https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/${TEXLIVE_RELEASE}/tlnet-final/"}"
: "${TEXLIVE_TARBALL:=install-tl-unx.tar.gz}"

function die() {
    echo "$@" >&2
    exit 1
}

function get-texlive-installer() {
    # download, checksum, extract
    curl --silent --location --remote-name-all "${TEXLIVE_MIRROR}/${TEXLIVE_TARBALL}"{,.sha512}
    # does not work 50% of the time shasum --check "${TEXLIVE_TARBALL}.sha512"
    tar --extract --gzip --file "${TEXLIVE_TARBALL}"
}

function texlive-profile() {
    cat <<EOF
	selected_scheme scheme-small
	TEXDIR $HOME/texlive
	TEXMFCONFIG $HOME/.texlive/texmf-config
	TEXMFHOME $HOME/texmf
	TEXMFLOCAL $HOME/texlive/texmf-local
	TEXMFSYSCONFIG $HOME/texlive/texmf-config
	TEXMFSYSVAR $HOME/texlive/texmf-var
	TEXMFVAR $HOME/.texlive/texmf-var
	option_doc 0
	option_src 0
EOF
}

function install-texlive() {
    local installer

    get-texlive-installer

    # find installer path from archive listing, sanity check
    installer="$(tar --list --gzip --file "${TEXLIVE_TARBALL}" | grep '/install-tl$' )"
    [[ -x "$installer" ]] || die "can not find TeXlive installer at ${installer}";

    texlive-profile >> texlive.profile
    "$installer" --repository "$TEXLIVE_MIRROR" --profile texlive.profile
    #PATH=/usr/local/texlive/${TEXLIVE_RELEASE}/bin/$(ls /usr/local/texlive/${TEXLIVE_RELEASE}/bin/ 2>/dev/null | head -1):$PATH
    tlmgr init-usertree
    tlmgr install latexmk luatex85
}

# Only call the main function if this script was called as a command. This makes
# it possible to source this script as a library.
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
    install-texlive
fi
