initialization
initAnnotatedKeywords
	self addAnnotatedKeywords: 'CAUTION:' to: 'caution';
		  addAnnotatedKeywords: 'IMPORTANT:' to: 'important';
		  addAnnotatedKeywords: 'IMPORTANT:' to: 'todo';
		  addAnnotatedKeywords: 'NOTE:' to: 'note';
		  addAnnotatedKeywords: 'NOTE:' to: 'annotation';
		  addAnnotatedKeywords: 'NOTE:' to: 'comment';
		  addAnnotatedKeywords: 'TIP:' to: 'tip';
		  addAnnotatedKeywords: 'TIP:' to: 'tips';
		  addAnnotatedKeywords: 'WARNING:' to: 'warning'.