#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# This script upgrades the current pillar installation to given version

rm -rf /tmp/pillar && mkdir -p /tmp/pillar
git clone -b upgrade git@github.com:pillar-markup/pillar.git /tmp/pillar

cd /tmp/pillar
./scripts/build.sh

rm -rf ${__dir}
mv build ${__dir}
rm -rf /tmp/pillar