#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PHARO_VM="${__dir}/pharo"
PILLAR_IMAGE="${__dir}/Pharo.image"

#Read pillar command
command=$1
shift

# disable parameter expansion to forward all arguments unprocessed to the VM
set -f

# TODO: when Pharo knows how to return the correct "current working directory", we
# can remove the --baseDirectory from here. The current solution is
# problematic because it overrides any baseDirectory parameter of the
# pillar.conf file.
exec "${PHARO_VM}" "${PILLAR_IMAGE}" --no-default-preferences pillar "${command}" --baseDirectory="${PWD}" "$@"