SystemOrganization addCategory: #'Pillar-ExporterCore'!
SystemOrganization addCategory: 'Pillar-ExporterCore-Base'!
SystemOrganization addCategory: 'Pillar-ExporterCore-Configuration'!
SystemOrganization addCategory: 'Pillar-ExporterCore-Description'!
SystemOrganization addCategory: 'Pillar-ExporterCore-Exceptions'!
SystemOrganization addCategory: 'Pillar-ExporterCore-Export'!
SystemOrganization addCategory: 'Pillar-ExporterCore-Utilities'!
