SystemOrganization addCategory: #'Pillar-Tests-Model'!
SystemOrganization addCategory: #'Pillar-Tests-Model-Core'!
SystemOrganization addCategory: #'Pillar-Tests-Model-Document'!
SystemOrganization addCategory: #'Pillar-Tests-Model-ScriptLanguage'!
SystemOrganization addCategory: 'Pillar-Tests-Model-Visitor'!
SystemOrganization addCategory: #'Pillar-Tests-Model-Visitor'!
stemOrganization addCategory: 'Pillar-Tests-Model-Visitor'!
