"
I'm representing the fact that the pillar edition chain can accept microdown as input. 
Now Microdown is converted into MicObjects, then pillar objects. 
The Microdown-Pillar and rich text packages should probably be added to this project (this will remove the dependency to pillar from microdown).
"
Class {
	#name : #ManifestBaselineOfPillarMicro,
	#superclass : #PackageManifest,
	#category : #'BaselineOfPillarMicro-Manifest'
}
